import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter, Plus_Jakarta_Sans } from 'next/font/google';
import GlobalToast from '@/components/global-toast';
import './globals.css';
import NextAuthSessionProvider from '@/contexts/session-provider';

const plusJakarta = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${inter.variable}  bg-[#E8E8E8]  ${plusJakarta.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <GlobalToast />
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
